name: build-push-restart

on:
  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: neilk3/website:latest
          cache-from: type=registry,ref=neilk3/website:latest
          cache-to: type=inline
  azure-restart-container:
    runs-on: ubuntu-latest
    # See for login details: https://github.com/Azure/login#configure-deployment-credentials
    steps:
      - 
        name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - 
        name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container restart --name ${{ secrets.AZURE_CONTAINER }} --resource-group ${{ secrets.AZURE_RG }}